/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package telas; 

import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class telaprincipal extends javax.swing.JFrame {
   int x;
   int y;
    public telaprincipal() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TP1 = new javax.swing.JRadioButton();
        TP2 = new javax.swing.JRadioButton();
        TP3 = new javax.swing.JRadioButton();
        TP4 = new javax.swing.JRadioButton();
        TP5 = new javax.swing.JRadioButton();
        TP6 = new javax.swing.JRadioButton();
        TP7 = new javax.swing.JRadioButton();
        TP8 = new javax.swing.JRadioButton();
        TP9 = new javax.swing.JRadioButton();
        TP10 = new javax.swing.JRadioButton();
        TP11 = new javax.swing.JRadioButton();
        TP12 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BSemanall = new javax.swing.JRadioButton();
        BMensal = new javax.swing.JRadioButton();
        BAnual = new javax.swing.JRadioButton();
        TPBCompra = new javax.swing.JButton();
        TPBOrcamento = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        TPMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Com capacidades de 10m3 a 20m3, nossa frota é");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("composta de basculantes 6x4 e 8x4, prontos para");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText(" as mais diversas condições.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Selecione os equipamentos");

        TP1.setBackground(new java.awt.Color(204, 204, 204));
        TP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP1.setText("Caminhão Basculante");
        TP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP1ActionPerformed(evt);
            }
        });

        TP2.setBackground(new java.awt.Color(204, 204, 204));
        TP2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP2.setText("Caminhão Pipa");
        TP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP2ActionPerformed(evt);
            }
        });

        TP3.setBackground(new java.awt.Color(204, 204, 204));
        TP3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP3.setText("Empilhadeira");
        TP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP3ActionPerformed(evt);
            }
        });

        TP4.setBackground(new java.awt.Color(204, 204, 204));
        TP4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP4.setText("Escavadeira");
        TP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP4ActionPerformed(evt);
            }
        });

        TP5.setBackground(new java.awt.Color(204, 204, 204));
        TP5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP5.setText("Gerador a diesel");
        TP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP5ActionPerformed(evt);
            }
        });

        TP6.setBackground(new java.awt.Color(204, 204, 204));
        TP6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP6.setText("Torre de iluminação");
        TP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP6ActionPerformed(evt);
            }
        });

        TP7.setBackground(new java.awt.Color(204, 204, 204));
        TP7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP7.setText("Trator de rodas");
        TP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP7ActionPerformed(evt);
            }
        });

        TP8.setBackground(new java.awt.Color(204, 204, 204));
        TP8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP8.setText("Trator de esteira");
        TP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP8ActionPerformed(evt);
            }
        });

        TP9.setBackground(new java.awt.Color(204, 204, 204));
        TP9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP9.setText("Plataforma elevatória");
        TP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP9ActionPerformed(evt);
            }
        });

        TP10.setBackground(new java.awt.Color(204, 204, 204));
        TP10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP10.setText("Mini-escavadeira");
        TP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP10ActionPerformed(evt);
            }
        });

        TP11.setBackground(new java.awt.Color(204, 204, 204));
        TP11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP11.setText("Motoniveladora");
        TP11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP11ActionPerformed(evt);
            }
        });

        TP12.setBackground(new java.awt.Color(204, 204, 204));
        TP12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TP12.setText("Rolo compactor");
        TP12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TP12ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Por quanto tempo?*");

        BSemanall.setBackground(new java.awt.Color(204, 204, 204));
        BSemanall.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BSemanall.setText("Semanal");
        BSemanall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSemanallActionPerformed(evt);
            }
        });

        BMensal.setBackground(new java.awt.Color(204, 204, 204));
        BMensal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BMensal.setText("Mensal");
        BMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMensalActionPerformed(evt);
            }
        });

        BAnual.setBackground(new java.awt.Color(204, 204, 204));
        BAnual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BAnual.setText("Anual");
        BAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnualActionPerformed(evt);
            }
        });

        TPBCompra.setText("Seguir com a compra");
        TPBCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPBCompraActionPerformed(evt);
            }
        });

        TPBOrcamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/orcamento (16 x 16).jpg"))); // NOI18N
        TPBOrcamento.setText("Pedir Orçamento");
        TPBOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPBOrcamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TPBOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BSemanall)
                        .addGap(18, 18, 18)
                        .addComponent(BMensal)
                        .addGap(18, 18, 18)
                        .addComponent(BAnual)
                        .addGap(201, 201, 201)))
                .addComponent(TPBCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TPBCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAnual)
                    .addComponent(BMensal)
                    .addComponent(BSemanall)
                    .addComponent(TPBOrcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("Com capacidades de 10m3 a 20m3, nossa frota é");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("composta de basculantes 6x4 e 8x4, prontos para");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("as mais diversas condições.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("Equipados com bomba de sucção a vácuo,");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("canhão de bombeiro, espargidor, rabo de");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setText("pavão e lavador de rua frontal.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("Com alturas máximas de trabalho e ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setText("capacidades de carga que se encaixam");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("perfeitamente à suas necessidades");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("Máquinas de 13 a 48 toneladas,");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("convencionais e long reach, com");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setText("diferentes configuraçães");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setText("Ampla gama de potências para atender");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel19.setText("as mais diversas necessidades de suprimento");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setText("de energia, seja qual for o regime");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setText("Garantem a continuidade dos trabalhos");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("em obras e operações com total segurança");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel23.setText("em condições de pouca iluminação");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setText("Desde aplicações agrícolas até ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setText("movimentação de vagões em terminais,");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel26.setText("nossa frota conta com diversos tratores");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel27.setText("Força, precisão de confiabilidade.");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel28.setText("Nossa linha de tratores de esteira é");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel29.setText("composta de máquinas de 14 a 43 ton.");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel30.setText("Platafprmas articuladas, pantográficas,");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel31.setText("spider ou mastro, elétricas ou a diesel,");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel32.setText("prontas para amplas faixas de alturas.");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel33.setText("Mecanização, facilidade de operação e ");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel34.setText("alta produtividade na execução de serviços");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel35.setText("de pequeno porte ou em espaços reduzidos.");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel36.setText("Versatilidade no trabalho de solo:");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel37.setText("nivelamento, acabamento, aclives, taludes");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel38.setText("curvas de níveis e mistura de materiais.");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel39.setText("Equipamentos de marcas mais consagradas");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel40.setText("do mundo disponíveis para locação.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TP4)
                            .addComponent(TP2)
                            .addComponent(TP3)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TP1)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))))
                                .addGap(199, 199, 199)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TP8)
                                    .addComponent(TP7)
                                    .addComponent(TP6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TP5)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TP10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TP9))
                            .addComponent(TP11)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel32)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel35)))
                            .addComponent(TP12)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel38)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel39))))
                        .addGap(68, 68, 68)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TP1)
                    .addComponent(TP5)
                    .addComponent(TP9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel18)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel19)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel21)
                    .addComponent(jLabel32))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TP6)
                    .addComponent(TP2)
                    .addComponent(TP10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel20)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel22)
                    .addComponent(jLabel34))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel23)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TP7)
                    .addComponent(TP3)
                    .addComponent(TP11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel24)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel25)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel26)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TP8)
                    .addComponent(TP4)
                    .addComponent(TP12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel27)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel28)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel29))
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {TP10, TP11, TP12, TP9});

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        TPMenu.setText("Menu");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Feedback");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        TPMenu.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Sair da Conta");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        TPMenu.add(jMenuItem3);

        jMenuBar1.add(TPMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       new telafeedback (). show ();
       setVisible(false); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      new telalogin (). show ();
       setVisible(false); 
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void TPBOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPBOrcamentoActionPerformed
        
        if ( BMensal.isSelected() == true || BAnual.isSelected() == true || BSemanall.isSelected() == true && x != 0) {
          JOptionPane.showMessageDialog(null,"O valor total dos ítens selecionados é "+x*y+ "$ reais");
       } else {
           JOptionPane.showMessageDialog(null, "Selecione um ítem e tempo para fazer o orçamento");
       } 
    }//GEN-LAST:event_TPBOrcamentoActionPerformed

    private void TPBCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPBCompraActionPerformed
    
        if ( BMensal.isSelected() == true || BAnual.isSelected() == true || BSemanall.isSelected() == true && x != 0) {
          JOptionPane.showMessageDialog(null,"O valor total dos ítens selecionados é "+x*y+ "$ reais");
          
           new telacompra (). show ();
       setVisible(false); 
        
       } else {
           JOptionPane.showMessageDialog(null, "Selecione um ítem e tempo para fazer uma compra");
       } 
        
      }//GEN-LAST:event_TPBCompraActionPerformed

    private void BSemanallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSemanallActionPerformed
   if(BMensal.isSelected() == true   ) {
        BMensal.setSelected(false);
      
               
   }
   if (BAnual.isSelected() == true) {
       BAnual.setSelected(false);
   }
  
   y = 2;     
    
        
    }//GEN-LAST:event_BSemanallActionPerformed
   
    private void TP12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP12ActionPerformed
  if (TP12.isSelected() == true) {
               x = x+200;
          
       } else {
           x = x-200;
          
       }    }//GEN-LAST:event_TP12ActionPerformed

    private void TP11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP11ActionPerformed
  if (TP11.isSelected() == true) {
               x = x+190;
          
       } else {
           x = x-190;
          
       }    }//GEN-LAST:event_TP11ActionPerformed

    private void TP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP10ActionPerformed
  if (TP10.isSelected() == true) {
               x = x+180;
          
       } else {
           x = x-180;
          
       }    }//GEN-LAST:event_TP10ActionPerformed

    private void TP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP9ActionPerformed
  if (TP9.isSelected() == true) {
               x = x+350;
          
       } else {
           x = x-350;
          
       }    }//GEN-LAST:event_TP9ActionPerformed

    private void TP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP8ActionPerformed
  if (TP8.isSelected() == true) {
               x = x+120;
          
       } else {
           x = x-120;
          
       }    }//GEN-LAST:event_TP8ActionPerformed

    private void TP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP7ActionPerformed
  if (TP7.isSelected() == true) {
               x = x+140;
          
       } else {
           x = x-140;
          
       }    }//GEN-LAST:event_TP7ActionPerformed

    private void TP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP6ActionPerformed
  if (TP6.isSelected() == true) {
               x = x+130;
          
       } else {
           x = x-130;
          
       }    }//GEN-LAST:event_TP6ActionPerformed

    private void TP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP5ActionPerformed
  if (TP5.isSelected() == true) {
               x = x+80;
          
       } else {
           x = x-80;
          
       }    }//GEN-LAST:event_TP5ActionPerformed

    private void TP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP4ActionPerformed
  if (TP4.isSelected() == true) {
               x = x+250;
          
       } else {
           x = x-250;
          
       }    }//GEN-LAST:event_TP4ActionPerformed

    private void TP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP3ActionPerformed
  if (TP3.isSelected() == true) {
               x = x+150;
          
       } else {
           x = x-150;
          
       }    }//GEN-LAST:event_TP3ActionPerformed

    private void TP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP2ActionPerformed
  if (TP2.isSelected() == true) {
               x = x+100;
          
       } else {
           x = x-100;
          
       }    }//GEN-LAST:event_TP2ActionPerformed

    private void TP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TP1ActionPerformed
       if (TP1.isSelected() == true) {
               x = x+50;
          
       } else {
           x = x-50;
          
       }
        
   
    }//GEN-LAST:event_TP1ActionPerformed

    private void BMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMensalActionPerformed
       if(BSemanall.isSelected() == true) {
        BSemanall.setSelected(false);
    }
       if (BAnual.isSelected() == true) {
       BAnual.setSelected(false);
   }
   y= 7;
    }//GEN-LAST:event_BMensalActionPerformed

    private void BAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnualActionPerformed
         if(BSemanall.isSelected() == true) {
            BSemanall.setSelected(false);
         }
         if (BMensal.isSelected() == true) {
             BMensal.setSelected(false);
         } 
         y= 72;
    }//GEN-LAST:event_BAnualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new telaprincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BAnual;
    private javax.swing.JRadioButton BMensal;
    private javax.swing.JRadioButton BSemanall;
    private javax.swing.JRadioButton TP1;
    private javax.swing.JRadioButton TP10;
    private javax.swing.JRadioButton TP11;
    private javax.swing.JRadioButton TP12;
    private javax.swing.JRadioButton TP2;
    private javax.swing.JRadioButton TP3;
    private javax.swing.JRadioButton TP4;
    private javax.swing.JRadioButton TP5;
    private javax.swing.JRadioButton TP6;
    private javax.swing.JRadioButton TP7;
    private javax.swing.JRadioButton TP8;
    private javax.swing.JRadioButton TP9;
    private javax.swing.JButton TPBCompra;
    private javax.swing.JButton TPBOrcamento;
    private javax.swing.JMenu TPMenu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
